spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.25.66.65:3306/filtergate?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: shoesmall
    password: master
    filters: wall,mergeStat

#多数据源情况的配置
filtergate:
  muti-datasource:
    open: false
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.25.66.65:3306/filtergate?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: shoesmall
    password: master
    dataSourceNames:
    - master
    - slave